
services:
  web:
    build:
      context: ./src
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./src:/app/src"
    environment:
        - MONGO_URI=${MONGO_URI_LOCAL}
        # - MONGO_HOST=mongo
        # - MONGO_PORT=27017
        # - MONGO_DB=proyecto_db
        # - MONGO_USER=admin
        # - MONGO_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
     - app-networks
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=proyecto_db
    volumes:
      - mongo-data:/data/db
    networks:
     - app-networks

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongo
    networks:
     - app-networks
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"    
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-storage:/var/lib/grafana  
    networks:
      - app-networks
    depends_on:
      - mongo                
  

networks:
  app-networks:
    driver: bridge

volumes:
  mongo-data:
  grafana-storage:

